# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for node config tutorial
# Check https://circleci.com/docs/2.0/configuration-reference/ for basic config help
#
version: 2
jobs:
  build:
    working_directory: ~/four-pass-transport
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10.0
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run:
          name: NPM Install
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run: # run tests
          name: Test
          command: npm run test-mocha-report
      - run: # run code coverage
          name: Code Coverage
          command: npm test

      - store_test_results:
          # Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-reports
      - store_artifacts: # save test results as an artifact
          # Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-reports/mocha/test-results.xml
          prefix: tests
      - store_artifacts: # save code coverage results as an artifact
          # Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-reports/nyc/lcov.info
          prefix: coverage
